# Generated by Django 6.1.1 on 2026-10-03 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceselection',
            old_name='choice_text',
            new_name='choice_txt',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='published_date',
            new_name='date_pub',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_txt',
        ),
    ]
