# Generated by Django 6.1.1 on 2026-10-03 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_choice_text_choiceselection_choice_txt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choiceselection',
            old_name='choice_txt',
            new_name='choice_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='date_pub',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_txt',
            new_name='question_text',
        ),
    ]
